# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.web_crawler:
    class: AppBundle\Service\WebCrawler
    arguments: ['%crawler_config_keys%']
  app.page_queue_mananger:
    class: AppBundle\Service\DoctrinePageQueue
    arguments: ['@service_container']